services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: accessmanagerdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: postgres
      TZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    networks:
      - accessmanager-net
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d accessmanagerdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Base template
  app-base: &app-base
    image: accessmanager-api
    build: .
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/accessmanagerdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: postgres
      TZ: America/Sao_Paulo
    networks:
      - accessmanager-net
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  app1:
    <<: *app-base
    container_name: app1

  app2:
    <<: *app-base
    container_name: app2

  app3:
    <<: *app-base
    container_name: app3

  nginx:
    image: nginx:1.25
    container_name: nginx
    restart: always
    depends_on:
      app1:
        condition: service_healthy
      app2:
        condition: service_healthy
      app3:
        condition: service_healthy
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - accessmanager-net

networks:
  accessmanager-net:
    driver: bridge

volumes:
  pgdata:
